[package]
name = "derive-error-chain-tests-no-backtrace"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
publish = false

[dependencies]
error-chain = { version = "0.10.x", default-features = false }
derive-error-chain = { path = "../derive-error-chain" }
