language: rust
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly

script: cd $CRATE && cargo build --verbose && cargo run

env:
- CRATE=derive-error-chain-tests
- CRATE=derive-error-chain-tests-no-backtrace

sudo: false
