language: rust
rust:
- stable
- beta
- nightly

script:
- (if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cd derive-error-chain && cargo test --verbose; fi)
- (cd derive-error-chain-tests && cargo run --verbose)
- (cd derive-error-chain-tests-no-backtrace && cargo run --verbose)
- (if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cd derive-error-chain-tests-nightly && cargo run --verbose; else echo 'Skipping nightly-only test'; fi)

sudo: false
