[package]
name = "derive-error-chain-tests"
version = "0.1.0"
authors = ["Arnavion <arnavion@gmail.com>"]
publish = false

[dependencies]
error-chain = "0.11.x"
derive-error-chain = { path = "../derive-error-chain" }
